apiVersion: v1
kind: Secret
metadata:
  name: wordpress-db-secret
  namespace: {{ .Values.namespace.name }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-2"
type: Opaque
data:
  wordpress-db-password: {{ .Values.configMap.sysprepWindows.autounattend.Password | b64enc | quote }}
