apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.wordpressBeRdp.name }}
  namespace: {{ .Values.namespace.name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "3"
spec:
  selector:
    kubevirt.io/domain: wordpress-be
  ports:
    - name: rdp
      protocol: TCP
      port: 3389
      targetPort: 3389
      nodePort: {{ .Values.service.wordpressBeRdp.nodePort }}
  externalTrafficPolicy: Cluster
  type: NodePort
