apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/part-of: wordpress-demo
  name: {{ .Values.service.wordpressBe.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "4"
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    vm.kubevirt.io/name: wordpress-be
  sessionAffinity: None
  type: ClusterIP
