apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress-cache-be
    app.kubernetes.io/part-of: wordpress-demo
  name: {{ .Values.service.wordpressCache.name }}
  namespace: {{ .Values.namespace.name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: wordpress-cache-be
    component: redis-cache
  sessionAffinity: None
  type: ClusterIP
