apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/part-of: wordpress-demo
  name: {{ .Values.service.wordpressFe.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: wordpress-fe
  sessionAffinity: None
  type: ClusterIP
